/*
===============================================================================
Magnitude Analysis
===============================================================================
Purpose:
    - To quantify data and group results by specific dimensions.
    - For understanding data distribution across categories.

SQL Functions Used:
    - Aggregate Functions: SUM(), COUNT(), AVG()
    - GROUP BY, ORDER BY
===============================================================================
*/
-- Find total customers by countries
    SELECT country ,
    COUNT (customer_key) AS total_customer
    FROM gold.dim_customers
    GROUP BY country
    ORDER BY total_customer ASC

-- Find total customers by gender
SELECT gender ,
COUNT(customer_key) AS total_customer
FROM gold.dim_customers
GROUP BY gender 
ORDER BY total_customer ASC
-- Find total products by category
SELECT category ,
COUNT (product_key) AS total_product
FROM gold.dim_products
GROUP BY category 
ORDER BY total_product ASC
-- What is the average costs in each category?
SELECT category ,
AVG(cost) AS average_cost
FROM gold.dim_products
GROUP BY category 
ORDER BY average_cost ASC
-- What is the total revenue generated for each category?
SELECT
    p.category,
    SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_products p
    ON p.product_key = f.product_key
GROUP BY p.category
ORDER BY total_revenue DESC;
-- What is the total revenue generated by each customer?
SELECT
    c.customer_key,
    c.first_name,
    c.last_name,
    SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
    ON c.customer_key = f.customer_key
GROUP BY 
    c.customer_key,
    c.first_name,
    c.last_name
ORDER BY total_revenue DESC;
-- What is the distribution of sold items across countries?
SELECT
    c.country,
    SUM(f.quantity) AS total_sold_items
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
    ON c.customer_key = f.customer_key
GROUP BY c.country
ORDER BY total_sold_items DESC;

-- What is the total revenue generated by each customer?
SELECT 
cust.customer_id,
cust.first_name,
cust.last_name,
SUM(sal.sales_amount) as total_revenue
from gold.fact_sales sal
LEFT JOIN gold.dim_customers cust 
ON cust.customer_key = sal.customer_key
GROUP BY 
cust.customer_id,
cust.first_name,
cust.last_name
ORDER BY total_revenue desc ;
-- What is the total revenue generated for each category?
Select prod.category ,
SUM(sal.sales_amount) AS total_revenue
from gold.fact_sales sal
LEFT JOIN gold.dim_products prod
ON prod.product_key = sal.product_key
GROUP BY prod.category 
ORDER BY total_revenue DESC
-- What is the distribution of sold items across countries?
Select cust.country,
sum(sal.quantity) as total_sold_items
from gold.fact_sales sal
LEFT JOIN gold.dim_customers cust
ON cust.customer_key = sal.customer_key
GROUP BY cust.country 
ORDER BY total_sold_items desc ;